services:
  backend:
    image: golang:1.25
    container_name: backend
    environment:
      - GIN_MODE=release
      - TURNSTILE_SECRET=1x0000000000000000000000000000000AA
      - VALID_SOURCES=unknown,source1,source2
    working_dir: /app
    volumes:
      - ./backend:/app
      - ./data:/data
    ports:
      - "8080:8080"
    tty: true
    stdin_open: true
    restart: unless-stopped

  frontend:
    image: node:latest
    container_name: frontend
    environment:
      - VITE_API_ENDPOINT=http://localhost:8080/api/submit
    working_dir: /app
    volumes:
      - ./frontend:/app
    ports:
      - "3000:3000"
    tty: true
    stdin_open: true
    restart: unless-stopped
